---
name: hyprland-atomic
description: Fedora Atomic with Hyprland
base-image: ghcr.io/ublue-os/base-main
image-version: 42
modules:
  - type: akmods
    base: bazzite
    install:
      - nvidia-open
    nvidia-driver: nvidia-open
  - type: dnf
    repos:
      nonfree: rpmfusion
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree 
    repos:
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      - https://copr.fedorainfracloud.org/coprs/dejan/lazygit/repo/fedora-%OS_VERSION%/dejan-lazygit-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%OS_VERSION%/tofik-nwg-shell-fedora-%OS_VERSION%.repo
      - vscode.repo
    keys:
      - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
      - https://packages.microsoft.com/keys/microsoft.asc
    install:
      # Desktop packages
      - brave-browser
      - btop
      - code
      - docker-compose
      - discord
      - distrobox
      - evince
      - firefox
      - foot
      - gamescope
      - gamemode
      - gvfs
      - kitty
      - libva-intel-media-driver
      - lazygit
      - loupe
      - man-pages
      - mangohud
      - mc
      - neovim
      - nodejs-npm
      - nwg-look
      - podman
      - podman-tui
      - qalculate-gtk
      - ripgrep
      - speedtest-cli
      - thunderbird
      - tmux
      - vulkan-tools
      - tealdeer
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    remove:
      - google-noto-sans-balinese-fonts
  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - com.bitwarden.desktop
          - com.github.tchx84.Flatseal
          - com.github.iwalton3.jellyfin-media-player
          - com.moonlight_stream.Moonlight
          - com.slack.Slack
          - com.stremio.Stremio
  - type: systemd
    system:
      enabled:
        - cosmic-greeter.service
        - docker.service
  - type: signing






