---
name: hyprland-atomic
description: Fedora Atomic with Hyprland
base-image: ghcr.io/ublue-os/base-main
image-version: 42
modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree 
    repos:
      files:
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      nonfree: rpmfusion
      copr:
        - dejan/lazygit
        - solopasha/hyprland
    install:
      packages:
        - hyprland
        - hyprpaper
        - hyprpicker
        - hypridle
        - hyprlock
        - hyprpolkitagent
        - hyprshot
        - uwsm
        - xdg-desktop-portal-hyprland
        - brave-browser
        - btop
        - direnv
        - discord
        - evince
        - eza
        - firefox
        - foot
        - gnome-text-editor
        - kitty
        - libva-intel-media-driver
        - lazygit
        - loupe
        - man-pages
        - mc
        - neovim
        - nodejs-npm
        - podman
        - podman-compose
        - podman-tui
        - qalculate-gtk
        - ripgrep
        - speedtest-cli
        - SwayNotificationCenter
        - thunderbird
        - tmux
        - vulkan-tools
        - waybar
        - wlogout
        - tealdeer
        - zsh
        - zsh-autosuggestions
        - zsh-syntax-highlighting
    remove:
      packages:
        - google-noto-sans-balinese-fonts
  - type: default-flatpaks
    system:
      install:
        - com.bitwarden.desktop
        - com.github.tchx84.Flatseal
        - com.github.iwalton3.jellyfin-media-player
        - com.moonlight_stream.Moonlight
        - com.slack.Slack
        - com.stremio.Stremio
        - com.visualstudio.code
  - type: signing
